### PR TITLE
HomeContainerAdapt add screen size condition

### PR DESCRIPTION
**Pull request by Buko-pie**
Reference issue https://github.com/mgguild/gamevault-frontend/issues/215

Capture

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
Ano na itsura neto? @Buko-pie 
image

**Comment by Buko-pie** [comment]
anong resoulution mo @kojiadrianojr ? ma add pa ata ako ki media querie

**Comment by Emman1598** [comment]
@Buko-pie, sa resolution ko, need pa i scroll down para mahiling su binance and ethereum logos. Pa revvise man, su dapat na iiling pati su ethereum and binance logo for any resolution. hehe. salamats!


image

**Review by Emman1598 — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]
AMDd

**Pull request merged**
