### PR TITLE
Fixed APR insufficient token prompt, UI Polishes

### PR DESCRIPTION
**Pull request by Buko-pie**
- includes fix for https://github.com/mgguild/gamevault-frontend/issues/279
- modal prompt w/ swap link if user has insufficient tokens when staking
- found bugs and fix

### CODE REVIEW

**Comment by EAdornado** [comment]
Remove Scroll on insufficient token prompt, modal size and texts should adjust depending on the devices used or resolution.
image

**Comment by EAdornado** [comment]
There's a memory leak encountered. 
image

**Review by EAdornado — APPROVED** [review]
All goods!

**Review by medardm — COMMENTED** [review]
LGTM

**Pull request merged**
