### PR TITLE
152 153 154 155 156 fix multiple issues

### PR DESCRIPTION
**Pull request by kojiadrianojr**
References #152 #153 #154 #155 #156 

- [ ] Fix margins 
- [ ] Maximize spacing
image
- [ ] Add tabs details
* Added feature to connect wallet in the allocations tab
tab details
- [ ] Center Status button
image
- [ ] Update website title per Guildpad
website title

### CODE REVIEW

**Comment by kojiadrianojr** [comment]
Update on title: 
image

**Review by Emman1598 — APPROVED** [review]

**Review by swengr-janan — APPROVED** [review]
Fixilated!

**Review by Buko-pie — APPROVED** [review]

**Comment by kojiadrianojr** [comment]
@Emman1598 gawin mo naman green yung check pri :< hahahahaha

**Review by Emman1598 — APPROVED** [review]

**Review by medardm — APPROVED** [review]
LGTM

**Pull request merged**
