### PR TITLE
78 fix issue

### PR DESCRIPTION
**Pull request by Buko-pie**
Reference issue https://github.com/mgguild/gamevault-frontend/issues/78

- Updated TanksWarsZone data and UI info in launchpad page

Capture

### CODE REVIEW

**Review by kojiadrianojr — APPROVED** [review]
Updated

**Comment by Buko-pie** [comment]
@swengr-janan sa develop branch ata yung fixed na

**Comment by kojiadrianojr** [comment]
For live page lang. Oks tong update kasi for page launchpad and updated na yung types.

**Review by swengr-janan — APPROVED** [review]

**Comment by swengr-janan** [comment]
Thanks @kojiadrianojr @Buko-pie

**Pull request merged**
