### PR TITLE
Update input staking component

### LINKED ISSUE #257: Update GameFi components

### PR DESCRIPTION
**Pull request by kojiadrianojr**
closes #257 

* Create component for input section

### CODE REVIEW

**Review by Emman1598 — APPROVED** [review]

**Comment by kojiadrianojr** [comment]
Updates: 
* Fix card rendering on GameFi homepage

**Review by Emman1598 — CHANGES_REQUESTED** [review]
@kojiadrianojr , pa fix kaini, naraot su mga cards 
image

Tapos apg tiga click su sa BUSD na card, naga erorr su sa bg
image

**Comment by kojiadrianojr** [comment]
try mo yung sa 2nd ata card muna kasi kulang yata yung sinupply na data for that

**Comment by kojiadrianojr** [comment]
Alam ko kasi dapat left side is farms, right side is lp

**Comment by kojiadrianojr** [comment]
Updated! @Emman1598

**Review by Emman1598 — APPROVED** [review]
All Goods!

**Pull request merged**
